### PR TITLE
add Pokemon Center and test

### PR DESCRIPTION
**Pull request by dulphyj**
Center's class, it's simple now, it just regenerates 100% health of a pokemon

### CODE REVIEW

**Comment by Dru27** [comment]
Good job! I think that you could change the atribute of affectHP method from pokemon to pokemon team.

**Comment by dulphyj** [comment]
> Good job! I think that you could change the atribute of affectHP method from pokemon to pokemon team.
Okay Diana, good observation, I'll do that

**Comment by dulphyj** [comment]
Make the suggested changes, you now receive a team pokemon

**Comment by Dru27** [comment]
Good job!

**Review by Dru27 — APPROVED** [review]

**Pull request merged**
