### PR TITLE
Implement startTournament function

### PR DESCRIPTION
**Pull request by eliosfg**

### CODE REVIEW

**Review by jimytz — APPROVED** [review]

**Comment by adrianovi** [comment]
You could implement a Test case creating an experimented trainer with a tough Pokemon that wins all the battles and allows the trainer to get a badge.
The same logic using a weak pokemon that makes the trainer lose and do not get a badge.

**Comment by adrianovi** [comment]
Good job

**Review by adrianovi — APPROVED** [review]
Ok

**Review by Agustin-Mediotti — APPROVED** [review]

**Comment by Agustin-Mediotti** [comment]
Nice one @vladitm19

**Pull request merged**
