### PR TITLE
Saul/commands fight use

### PR DESCRIPTION
**Pull request by eliosfg**

### CODE REVIEW

**Review by lechemon4000 — APPROVED** [review]
Good job! 👍

**Review by adrianovi — APPROVED** [review]
Nice

**Review by Dru27 — APPROVED** [review]

**Comment by Dru27** [comment]
👍!!!

**Review by Agustin-Mediotti — APPROVED** [review]
💯 Excellent Job!

**Review by vladitm19 — APPROVED** [review]

**Review by vladitm19 — APPROVED** [review]
Good job!

**Pull request merged**
